### ISSUE TITLE
App crashes shortly after launching  In telemetry module

### ISSUE THREAD

**Issue by nickruddeni** [segmentio/analytics-swift#371] opened 2024-11-15 13:35 UTC
**Describe the bug**

App crashes shortly after launching 

**To Reproduce**
This started showing up this morning whilst I was testing out WatchOS up. We are using "Up to next major version" versioning on Segment and thus build with version 1.7 that appears to have just been released.

Seems to be a deadlock within the Telemetry module when syncing on the telemetryQueue

**Expected behavior**
Doesn't crash

**Screenshots**

![Screenshot 2024-11-15 at 13 32 36](https://github.com/user-attachments/assets/fb9d8bcc-e2f0-4e2e-b1f4-116768b58233)

**Platform (please complete the following information):**
 - Library Version in use: 1.7.0
 - Platform being tested: WatchOS 10.4
 - Integrations in use: no device mode integrations

**Comment by MichaelGHSeg** [comment] 2024-11-15 17:05
Thank you for the report, I'm investigating this now.

**Comment by waseemshahzad-mset** [comment] 2024-11-15 18:20
telemetryQueue deadlock issue 

App crashes right after launching

To Reproduce:
We are using "Up to next major version" versioning on Segment 1.7.0 that appears to have just been released.
Seems to be a deadlock within the Telemetry module when syncing on the telemetryQueue

Expected Behavior:
App should not crash 

Logs are attached below:

<img width="1132" alt="telemetryQueu" src="https://github.com/user-attachments/assets/516ed4b9-892f-4f3c-9ea1-5adf093ba830">
<img width="1445" alt="analytics" src="https://github.com/user-attachments/assets/bb07ba1d-e088-4467-90a2-18a7032944fe">

**Comment by bsneed** [comment] 2024-11-15 18:21
We've got an engineer looking at it; should be fixed shortly.

**Comment by Elipasousa** [comment] 2024-11-18 13:00
We're seeing the same after updating to `1.7.0` on platform `macOS`. Following for updates

**Comment by MichaelGHSeg** [comment] 2024-11-18 20:21
1.7.1 is out and should fix these issues.

**Closed as completed by MichaelGHSeg** 2024-11-18 20:21 UTC
Labels: triage
